import Head from 'next/head'
import Body from '../components/Body'
import Header from '../components/Header'
import Section from '../components/Section'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Docs Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Section />
      <Body />
      
    </div>
  )
}
